services:
  - type: web
    plan: free
    name: api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80"
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
